name: app_controles
description: App movil de controles y alertas.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.2
  local_auth: ^2.3.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.3
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon_master.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 21
